version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test1161Project
  gitServerName: Dima
  gitUrl: https://github.com/deemashlayer/Test1161Project
  gitUsername: deemashlayer
  gitBranch: main
services:
- serviceName: project.test1161.integrations:testMath1
  packages:
  - name: Test1161Project
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.686
